05 Basic Event Implementation
akai-org/akaitodo-backend pull request #20
Opened 2024-03-29 21:59 UTC by smazik02

- Implemented a basic event entity with all essential fields
- Created an endpoint with basic CRUD operations
- Added API tests for Bruno API client
- Fixed a bug in an edit user action

2024-04-02 22:45 UTC, Aeri4a requested changes
GJ. Small things, good start

2024-04-02 22:45 UTC, Aeri4a commented on src/resource/events/event.service.ts
> +        if (!event) throw new NotFoundException('Note not found');
Note not found :D

2024-04-02 22:45 UTC, Aeri4a commented on src/resource/events/event.service.ts
> +        if (affected == 0) throw new NotFoundException("Note doesn't exist");
Michał will be angry

2024-04-03 11:11 UTC, m-olej commented on src/resource/events/event.service.ts
> +        if (affected == 0) throw new NotFoundException("Note doesn't exist");
>:(

2024-04-03 12:40 UTC, smazik02 commented on src/app.module.ts
> +import { EventModule } from './resource/events/event.module';
I followed Michał's naming convention, I think we need a refactor for both in that case

2024-04-03 12:40 UTC, smazik02 commented on src/database/entities/event.entity.ts
> +    createdBy: UserEntity;
This makes things 1000 times easier and I don't know of a more "elegant" solution

2024-04-03 12:41 UTC, smazik02 commented on src/database/entities/user.entity.ts
> +    events: EventEntity[];
It's more of a formality, I don't think we'll ever use it. I need to check if removing it breaks stuff

2024-04-03 12:44 UTC, smazik02 commented on src/resource/events/dto/ReturnEvent.dto.ts
> +    endDate?: Date;
Maybe, I'll think about it

2024-04-03 12:52 UTC, smazik02 commented on src/resource/events/event.service.ts
> +        if (!event) throw new NotFoundException('Note not found');
Fixed

2024-04-03 12:52 UTC, smazik02 commented on src/resource/events/event.service.ts
> +        if (affected == 0) throw new NotFoundException("Note doesn't exist");
:)

2024-04-03 13:03 UTC, smazik02 commented on src/resource/events/dto/ReturnEvent.dto.ts
> +export class ReturnEventDto {
No

2024-04-03 18:26 UTC, smazik02 commented on src/database/entities/event.entity.ts
> +    createdBy: UserEntity;
I deleted them, they're not necessary

2024-04-03 18:28 UTC, smazik02 commented on src/resource/events/dto/ReturnEvent.dto.ts
> +    endDate?: Date;
Done

2024-04-03 18:34 UTC, smazik02 commented on src/app.module.ts
> +import { EventModule } from './resource/events/event.module';
Done

2024-04-03 18:35 UTC, smazik02 commented on src/database/entities/user.entity.ts
> +    events: EventEntity[];
Deleted them both

2024-04-03 18:35 UTC, smazik02 commented on src/resource/events/dto/CreateEvent.dto.ts
> +export class CreateEventDto {
Done

2024-04-03 18:35 UTC, smazik02 commented on src/resource/events/dto/EditEvent.dto.ts
> +export class EditEventDto {
Done

2024-04-04 19:46 UTC, merged